#!/bin/sh

has_app()
{
    hash $1 2>/dev/null
}

delete_group()
{
  if has_app groupdel; then
    groupdel $1
  elif has_app delgroup; then
    delgroup $1
  else
    echo Failed to delete a group, no supported group management utils found
    exit 1
  fi
}

delete_user()
{
  if has_app userdel; then
    userdel $1
  elif has_app deluser; then
    deluser $1
  else
    echo Failed to delete a user, no supported user management utils found
    exit 1
  fi
}

if test "x${REBUILD_TRACE}" = "x1"; then
  set -x
  echo Bootstrap tracing enabled
  DEBUG_TRACE=/dev/tty
else
  DEBUG_TRACE=/dev/null
fi
