CONF_DIR = File.join( Dir.home, '.rbld' )
RBLD_CONF = File.expand_path( 'rebuild.conf', CONF_DIR )

CONF_CONTENTS = <<TEXT
#This is a sample config file for Rebuild
#Uncomment and adjust following lines
#according to your registry configuration

#For Docker registries
#REMOTE_NAME=origin
#REMOTE_TYPE_origin="docker"
#REMOTE_origin="10.0.110.110:5000"

#For native Rebuild registry
#REMOTE_NAME=origin
#REMOTE_TYPE_origin="rebuild"
#REMOTE_origin="/mnt/rbld_regsitry_root"

#For Docker Hub
REMOTE_NAME=origin
REMOTE_TYPE_origin="dockerhub"
REMOTE_origin="rbld/environments"
TEXT

task default: [RBLD_CONF]

file RBLD_CONF do
  FileUtils.mkdir_p( CONF_DIR )

  unless File.exist?( RBLD_CONF )
    open(RBLD_CONF, 'w') do |f|
      f.write CONF_CONTENTS
    end
  end
end

task :RBLD_CONF_DELETE do |t|
  FileUtils.rm_f( RBLD_CONF )
end

task force: [:RBLD_CONF_DELETE, RBLD_CONF]
