#!/bin/bash

rebuild_prefix=`dirname $BASH_SOURCE`/../
. $rebuild_prefix/libexec/re-build-globals

function show_usage
{
    echo
    echo Usage: $rebuild_app_name rm [OPTIONS] ENVIRONMENT[:TAG]
    echo
    echo Remove local environment
    echo
    echo "  -h, --help          Print usage"
    echo
}

function env_ctx_directory
{
    local NAME=$1
    echo $rebuild_home/env-$NAME
}

args=$(getopt -l "help" -o "h" -- "$@")

eval set -- "$args"

while [ $# -ge 1 ]; do
    case "$1" in
        --)
            # No more options left.
            shift
            break
           ;;
        -h|--help)
            show_usage
            exit 0
            ;;
    esac

    shift
done

env_name=`rebuild_cmd_line_env_name $*`
env_tag=`rebuild_cmd_line_env_tag $*`

if [[ -z $env_name ]]; then
    handle_error "Environment name not specified"
fi

if rebuild_env_dirty $env_name $env_tag; then
    handle_error "Environment is modified, commit or checkout first"
fi

rebuild_verify_env_exists $env_name $env_tag
rebuild_delete_image $env_name $env_tag
