#!/bin/bash -e

function has_app
{
    hash $1 2>/dev/null
}

function dep_install
{
    if has_app dnf; then
        dnf install -y $*
        #cleaning to make image smaller
        dnf clean all
    elif has_app yum; then
        yum install -y $*
        #cleaning to make image smaller
        yum clean all
    elif has_app apt-get; then
        apt-get update
        apt-get install -y $*
        #cleaning to make image smaller
        apt-get clean
    else
        echo Failed to install "$*", no supported package manager found
        exit 1
    fi
}

if ! has_app sudo; then
    dep_install sudo
fi
