#!/bin/bash

rebuild_prefix=`dirname $BASH_SOURCE`/../
. $rebuild_prefix/libexec/re-build-globals

function show_usage
{
    echo
    echo Usage: $rebuild_app_name load [OPTIONS] FILE
    echo
    echo Load environment from file
    echo
    echo "  -h, --help               Print usage"
    echo
}

function do_load
{
  local FILE=$1

  RC=0
  gunzip -c $FILE | { docker load || RC=1; } | filter_debug

  # If images with the same name but another
  # ID existed before load they become dangling
  # and it is better to ditch them
  rebuild_delete_dangling_images

  return $RC
}

args=$(getopt -l "help" -o "h" -- "$@")

eval set -- "$args"

while [ $# -ge 1 ]; do
    case "$1" in
        --)
            # No more options left.
            shift
            break
           ;;
        -h|--help)
            show_usage
            exit 0
            ;;
    esac

    shift
done

if [[ -z ${1+x} ]]; then
    handle_error "File name must be specified"
fi

file_name=$1

if [[ ! -f $file_name ]]; then
    handle_error "File $file_name does not exist"
fi

RC=0
do_load $file_name || RC=1

if [[ $RC -eq 0 ]]; then
    report_progress "Successfully loaded environment from $file_name"
else
    report_progress "Failed to load environment from $file_name"
fi

exit $RC
