#!/bin/bash

rebuild_prefix=`dirname $BASH_SOURCE`/../
. $rebuild_prefix/libexec/re-build-globals

function show_usage
{
    echo
    echo Usage: $rebuild_app_name list [OPTIONS]
    echo
    echo List local environments
    echo
    echo "  --help            Print usage"
    echo
}

args=$(getopt -l "help" -o "h" -- "$@")

eval set -- "$args"

while [ $# -ge 1 ]; do
    case "$1" in
        --)
            # No more options left.
            shift
            break
           ;;
        -h|--help)
            show_usage
            exit 0
            ;;
    esac

    shift
done

echo

rebuild_list_images         | \
    awk '{print $1 ":" $2}' | \
    rebuild_strip_env_name  | \
    sort                    | \
    sed -e 's/^/\t/'

echo