#!/bin/bash

rebuild_prefix=`dirname $BASH_SOURCE`/../
. $rebuild_prefix/libexec/re-build-globals

function show_usage
{
    echo
    echo Usage: $rebuild_app_name publish [OPTIONS] ENVIRONMENT[:TAG]
    echo
    echo Publish environment at remote registry
    echo
    echo "  -h, --help          Print usage"
    echo
}

function do_publish
{
    local NAME=$1
    local TAG=$2
    local REMOTE=`rebuild_get_remote`

    if [[ -z $REMOTE ]]; then
        handle_error "Remote not defined"
    fi

    local PUBLISHED_NAME=`rebuild_published_env_name $REMOTE $NAME $TAG`

    report_progress "Checking for collisions..."

    if rebuild_is_published $PUBLISHED_NAME; then
        handle_error "Environment $env_name:$env_tag already published"
    fi

    report_progress "Publishing at $REMOTE..."

    docker tag `rebuild_env_name $NAME`:$TAG $PUBLISHED_NAME | filter_debug
    colorize_trace docker push $PUBLISHED_NAME
    docker rmi $PUBLISHED_NAME | filter_debug

    report_progress "Successfully published $NAME:$TAG"
}

args=$(getopt -l "help" -o "h" -- "$@")

eval set -- "$args"

while [ $# -ge 1 ]; do
    case "$1" in
        --)
            # No more options left.
            shift
            break
           ;;
        -h|--help)
            show_usage
            exit 0
            ;;
    esac

    shift
done

env_name=`rebuild_cmd_line_env_name $*`
env_tag=`rebuild_cmd_line_env_tag $*`

if [[ -z $env_name ]]; then
    handle_error "Environment name not specified"
fi

rebuild_verify_env_exists $env_name $env_tag

if rebuild_env_dirty $env_name $env_tag; then
    handle_error "Environment is modified, commit or checkout first"
fi

do_publish $env_name $env_tag
